version: "3.8"
services:
  backend:
    build: .
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000